pipeline{
    agent any
    tools {
        maven 'maven'
    }
    stages{
        stage("Git Checkout"){
            steps{
                git branch: 'main', url: 'https://github.com/SiddheshMali/ecommerce.git'
            }
        }
        stage("Go to backend folder"){
            steps{
                sh 'mvn -f ./backend/pom.xml clean package -DskipTests=true'
            }
        }
        stage("Static Code analysis")
        {
            steps{
                script{
                    withSonarQubeEnv(credentialsId: 'sonar-api-2'){
                        sh 'mvn -f ./backend/pom.xml clean verify sonar:sonar \
                                    -Dsonar.projectKey=shopapp \
                                    -Dsonar.host.url=http://52.140.116.252:9000 \
                                    -Dsonar.login=sqp_cccdf9e8c2f5c7c40d08ba6a42cfffe593a74080'
                }
            }
        }
        }
        stage("Quatily Gate Analysis"){

              steps{

                  script{

                      waitForQualityGate abortPipeline: true, credentialsId: 'sonar-api-2'

                  }



              }

        }
        stage("nexus"){
            steps{
                script{
                    nexusArtifactUploader artifacts: [[artifactId: 'shop-api', classifier: '', file: './backend/target/ecommerce-spring-boot.jar', type: 'jar']], credentialsId: 'nexus-auth', groupId: 'me.zhulin', nexusUrl: '52.140.116.252:8081', nexusVersion: 'nexus3', protocol: 'http', repository: 'shopapp', version: '0.0.1-SNAPSHOT'
                }
            }
        }
        
        
    }
}
